Update new
There are two minor issues here.
1. The std is missing, so my compiler (arm-none-eabi-gcc (Arch Repository) 4.9.2 20150128 (prerelease)) won't compile anything, when I include <new> (std::size_t fixes this!)
2. Some new/delete signatures are missing, like new[] or delete[]. Just check your default arm <new> include file 



/usr/local/arm-none-eabi/include/stm32plus-040100/stl/new:12:20: error: declaration of 'operator new' as non-function
 void *operator new(size_t size_);
                    ^
/usr/local/arm-none-eabi/include/stm32plus-040100/stl/new:12:20: error: 'size_t' was not declared in this scope